### ISSUE TITLE
Direct downloads from Drive? (Was: Where do I get the latest stable source code?)

### ISSUE THREAD

**Issue by svetlemodry** [steve8x8/geotoad#325] opened 2015-08-12 17:47 UTC
Hi,
I'm the maintainer of the Arch Linux AUR [geotoad](https://aur.archlinux.org/packages/geotoad/) package. It seems the latest stable version is supposed to be the v3.23.1 already. Where can I download the source code for that particular version? There seem to be no usual tags or releases visible in this repository.
Thanks!

**Comment by steve8x8** [comment] 2015-08-22 14:26
I'm surprised there's a geotoad package for another Linux distro than Debian - and I would never have learned about that without the hassle caused by Google Code closing down.
(And there might be others lurking... Step forward now!)
To answer your - and perhaps other packagers' - question: In the Wiki (link at the right hand side) Home page, there's a "one size fits all" link to Google Drive, and with each release ("CurrentVersion" page) comes a pointer to the recent tarball (which would be your starting point). Apologies that I didn't manage proper release tagging yet, that's something I'll work on in the future - for now please use the tarball.

**Comment by steve8x8** [comment] 2015-08-30 13:45
Although there are now tags which are related to a release, the tarball produced by github isn't recommended as a starting point for whichever derivative work - e.g. the "VERSION" string is only substituted during my release process (check tools/build/Makefile for details).
Please use "my" published tarball, available from Google Drive, only. Links are here (wiki:CurrentVersion) and on freshcode.club/projects/geotoad - thanks, S

--- leaving this issue open for future reference ---

**Comment by svetlemodry** [comment] 2015-09-01 17:10
Thanks for the update. Is there a way how to point to a direct download link of the google disk tarball? I seem to be missing it or GDisk does not allow such functionality. I'm going for the tagged github tarball for now.

**Comment by steve8x8** [comment] 2015-09-02 12:10
I'd like to know this as well - I'd love to make deb packages available via sources.list entries again, but haven't figured out how to fit this into the GDrive context. Apparently, direct download links don't work as easily as GCode did :(
Anyone with more insight? *raising the "HELP!!!" flag*

**Comment by steve8x8** [comment] 2016-06-13 07:52
GitHub upon tagging a new release, creates a tarball ```https://github.com/steve8x8/geotoad/archive/${VERSION}.tar.gz```, and links it in https://github.com/steve8x8/geotoad/releases. 
While there are several places left with a %VERSION% placeholder (which I don't want to update with every possible release candidate), there's also a ```tools/build/Makefile``` which would get executed by me when preparing a release, and which contains the necessary ```sed``` replacements. 
I'm only using Debian, but I would consider adding RPM-style .spec and possibly other files to assist packaging.

**Comment by steve8x8** [comment] 2016-10-13 19:02
%VERSION% placeholders, in preparation of a release, get replaced with the actual string now. This makes sure that a tagged release is consistent.
On the other hand, the first commit after a release will revert this, marking the code as "work in progress". The version checker built into geotoad.rb will notice this and issue a mild complaint.

As long as you take a release tarball, you should be safe.

**Closed by steve8x8** 2016-10-13 19:02 UTC
